### ISSUE TITLE
Getting astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by dhruv-agarwal-rft** [tjarrettveracode/veracode-workspace-auto-create#1]
When running the below command:
C:\Users\UX501794\veracode-workspace-auto-create>python vcworkspace.py -a 47544
I am getitng below error:

Traceback (most recent call last):
  File "vcworkspace.py", line 141, in <module>
    main()
  File "vcworkspace.py", line 115, in main
    creds_expire_days_warning()
  File "vcworkspace.py", line 23, in creds_expire_days_warning
    delta = exp - datetime.datetime.now().astimezone() #we get a datetime with timezone...
ValueError: astimezone() cannot be applied to a naive datetime

The issue can be related to date time issue. Please could you help me with that.

**Comment by dhruv-agarwal-rft** [comment]
The issue can be closed. The issue was with the Python version.

**Comment by tjarrettveracode** [comment]
Thanks @dhruv-agarwal-rft -- was the issue Python 2 vs. 3? I should probably indicate that Python 3 is required.
